# .travis.yml
sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "ug4306@gmail.com"
  - git config --global user.name "egyeom"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "HtlSiworfnXEPrraV4XOj7yvN8xVK9y7Bp55tBXdCGZkxNitrQkX+O4u6v+nvr/oXjyekUtugdY9SZRkAlFFtCzIBjGcFd/pieQNDJSNuqbWVMxUmklLv0VHD3GuicGhz+vWkAEnU30sKq6p1LeXMTO/QWQd09J1lP3yUD2joH33KtGN6vQ2eC1kCOSf/KiahVNSJdcP64zJsyeBDYPq5fl9hcnN3WMd8Wlr+sTzPgbcLe6+/tbz6xNAD+S1rG081Cd5ZsF6dy830J2eSUawsYVmo8uS9DEt3pG9cHkx2LPz+UVn5UGOAGL70lLJIwRMT0co1V8MIYX7e3Szv0DuB/b+Bq6lnKsFHmzyuAVJ/CTttCDttM3/rPess4Lds7xW6xWS4QGqM/POi4mCcqsaFdjjA9QQyVZkOI/fh7/2mVWuIXMONwV8BiqeO0a3cgtHVOxjd+djrgDpTfbGSixkO+21TJHrrytEiGw+PHo/tamur/Csk2GhEXJq/wbOuTM171JWSgdHQP515dNjXcCn3eZujQJ+YAZOB1T7VpyhMuHM9CiTcDUGgQHmth4rcqzBcewdubkmm5PawIN/yFYvGySu55hX47jH2WbyhNDiMGuz/shcS20R2I/4+98nrx+jsajHffAQ1ICTEKZnsw6yIoh6NX0n4bNneZcTNzBmxL0="
branches:
  only:
    - master